### ISSUE TITLE
Suggestion to add 2  important features

### ISSUE THREAD

**Issue by nirbal** [ranbuch/accessibility#28]
To my point of view, the plugin is missing 2 important features in menu that regulators follow them  :
1. Area with button to redirect to Accesibilty Disclaimer URL that site owner publish.
2. Mailto button for reporting to site owner on accesibilty issue

**Comment by rtgfxp** [comment]
could these fields be added in the future?

**Comment by ranbuch** [comment]
I think we can add custom buttons. The developer will be able to determine the text on the button and catch the click event.

@nirbal @rtgfxp WDYT?

**Comment by rtgfxp** [comment]
Sounds good, we need to redirect to the accessibility disclaimer (link URL) and contact page.

**Comment by nirbal** [comment]
Seems good solution

**Comment by ranbuch** [comment]
@nirbal @rtgfxp I've added an option to add buttons that wiil open a model with an iframe. You can use it as follows:
```javascript
new Accessibility({
        iframeModals: [{
          buttonText: '[button text here]',
          iframeUrl: '[Iframe URL here]',
          icon: 'policy',
          emoji: '⚖️'
        }]
});
```
You can use other icon values from [here](https://mui.com/material-ui/material-icons/) and other [emojis](https://emojipedia.org/). In case you are using the default icons it will use the material design "icon" parameter, otherwise it will fallback to the emoji parameter.

Hoping to do the custom buttons sometimes soon.

**Comment by rtgfxp** [comment]
Works great, good job! @ranbuch

**Comment by ranbuch** [comment]
@rtgfxp Also added the custom functions feature:
```javascript
new Accessibility({
        customFunctions: [{
          method: (cf, state) => {
            console.log(cf, state);
          },
          buttonText: 'foo',
          id: 1,
          toggle: true,
          icon: 'psychology_alt',
          emoji: '❓'
        }]
});
```
Same behavior for the icons values as the `iframeModals` feature. Closing this issue but fill free to open another one in case something is not working as expected.

Thanks for your patience.
